log    = /scratch/abishop/ara/a23/sub_info_full/logs/A$(station).R$(run).log
output = /scratch/abishop/ara/a23/sub_info_full/out/A$(station).R$(run).out
error  = /scratch/abishop/ara/a23/sub_info_full/err/A$(station).R$(run).err

request_memory = 1GB
#request_disk = 2GB

Universe = vanilla
getenv = true
+TransferOutput = ""
should_transfer_files = YES
when_to_transfer_output = ON_EXIT

nice_user = false

executable = ARA_job.sh
arguments = $(station) $(run)

queue
